# Generated by Django 3.1 on 2020-08-21 23:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0003_auto_20200821_1647'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('accounts', django.db.models.manager.Manager()),
            ],
        ),
    ]
